version: '3.7'

services:

  crawler_db:
    image: postgres:11
    hostname: ${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - crawler_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - qchain

  job_crawler:
    hostname: ${CRAWLER_HOSTNAME}
    container_name: ${CRAWLER_HOSTNAME}
    restart: always
    build:
      context: ".."
      dockerfile: config/Dockerfile
      args:
        PROJECT_DIR: ${PROJECT_DIR}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - crawler_db
    networks:
      - qchain

networks:
  qchain:
    driver: bridge

volumes:
  crawler_db: