version: '3.4'

services:

  crawler_db:
    image: postgres:10
    hostname: ${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - crawler_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - qchain

networks:
  qchain:
    driver: bridge

volumes:
  crawler_db: