version: '3.7'

services:

  crawler_db:
    image: postgres:11
    hostname: ${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - crawler_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - qchain

#  job_crawler:
#    hostname: ${CRAWLER_HOSTNAME}
#    container_name: ${CRAWLER_HOSTNAME}
#    restart: always
#    build:
#      context: ".."
#      dockerfile: config/Dockerfile
#      args:
#        PROJECT_DIR: ${PROJECT_DIR}
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_HOST: ${CONTAINER_NAME}
#      SELENIUM_HUB: ${HUB_HOSTNAME}
#      HUB_PORT: ${HUB_PORT}
#    depends_on:
#      - crawler_db
#    networks:
#      - qchain

  selenium-hub:
    image: selenium/hub
    container_name: ${HUB_HOSTNAME}
    hostname: ${HUB_HOSTNAME}
    ports:
      - ${HUB_PORT}:4444
    depends_on:
      - crawler_db
    networks:
      - qchain
    environment:
      - GRID_BROWSER_TIMEOUT=120000
      - GRID_TIMEOUT=120000
      - GRID_CLEAN_UP_CYCLE=60000
      - GRID_MAX_SESSION=50
      - GRID_MAX_INSTANCES=3
      - JVM_OPTS=-Xmx10g
      - GRID_JETTY_MAX_THREADS=1500
    shm_size: 10g

  chrome:
    image: selenium/node-chrome:3.14.0-krypton
    environment:
      - HUB_PORT_4444_TCP_ADDR=${HUB_HOSTNAME}
      - HUB_PORT_4444_TCP_PORT=${HUB_PORT}
      - NODE_BROWSER_NAME=chrome
      - NODE_MAX_INSTANCES=500
      - NODE_MAX_SESSION=500
      - NODE_SELENIUM_PROTOCOL=WebDriver
      - JVM_OPTS=-Xmx24g
    ports:
      - 5900
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm --privileged

networks:
  qchain:
    driver: bridge

volumes:
  crawler_db: